### ISSUE TITLE
How to gulp production task?

### ISSUE THREAD

**Issue by tomkeysers** [chrismcintosh/bolt-pro#12]
Not sure how to get the production build going. From what I can see in the gulpfile a --production flag is used, but running `npm start build --production` doesn't result in a compressed stylesheet :/

How to do it? 

Thanks in advance! And by the way, thanks for this awesome starter theme!

**Comment by chrismcintosh** [comment]
The two commands are 

'npm start' for dev

And

'npm run build' for production 

Can you try 'npm run build'?

**Comment by tomkeysers** [comment]
Thanks @chrismcintosh , that works!
