### ISSUE TITLE
Failed to load external module @babel/register

### ISSUE THREAD

**Issue by tomkeysers** [chrismcintosh/bolt-pro#15]
Due to an hdd crash I'm pulling in a project from my git which is built upon this theme on a clean drive, but I'm getting an error during the `npm start` process.

Terminal says: `Failed to load external module @babel/register`
then proceeds the gulp process to 'watch'...
And then this error:
```
The following tasks did not complete: default, watch
Did you forget to signal async completion?
wordpress/wp-content/themes/themename/node_modules/ws/index.js:9
const WebSocket = require('./lib/WebSocket');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/xxx/wordpress/wp-content/themes/themename/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Server.init (/Users/xxx/wordpress/wp-content/themes/themename/node_modules/engine.io/lib/server.js:115:16)
    at new Server (/Users/xxx/wordpress/wp-content/themes/themename/node_modules/engine.io/lib/server.js:65:8)

npm ERR! Darwin 15.6.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE
npm ERR! foundation-zurb-template@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundation-zurb-template@1.0.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundation-zurb-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundation-zurb-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundation-zurb-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxx/wordpress/wp-content/themes/themename/npm-debug.log
```

Anyone an idea how to fix this?

**Comment by chrismcintosh** [comment]
Try running 'npm install @babel/register' also make sure you have the Babel presets in your .babelrc file

**Comment by chrismcintosh** [comment]
Sorry 'npm install @babel/register'

**Comment by chrismcintosh** [comment]
Won't let me your it from my phone I'll see if I can help when get back to my desktop

**Comment by tomkeysers** [comment]
I ran the npm install twice now (second time after removing all node_modules and `npm clean cache`) without any errors during install. Also ran `npm run build` and that seems to work fine. 

.babelrc contains:
```
{
  "presets": ["es2015"]
}
```

**Comment by chrismcintosh** [comment]
Double check that all your assets paths are valid in the config.yml

Make sure that your gulp tasks are returning something - see [Signal Async](https://stackoverflow.com/questions/36897877/gulp-error-the-following-tasks-did-not-complete-did-you-forget-to-signal-async)

Do you have a link for your repo?

**Comment by tomkeysers** [comment]
Apparently the problem had a deeper cause: my new home folder had a space in it which caused some node_modules to fail during installation – at least that's what it looks like and brought me to the solution. It's fixed now.

Thanks anyway @chrismcintosh for the quick help!
